
export const foodchooser ={
    menuItem:{
        '1':require('../assets/menuItems/cow.jpg'),
        '2':require('../assets/menuItems/pork.jpg'),
        '3':require('../assets/menuItems/goat.jpg'),
        '4':require('../assets/menuItems/sheep.jpg'),
        '5':require('../assets/menuItems/chicken.jpg'),
        '6':require('../assets/menuItems/duck.jpg'),
        '7':require('../assets/menuItems/fish.jpg'),
        '8':require('../assets/menuItems/fruits.jpg'),
        '9':require('../assets/menuItems/vegetables.jpg'),
        '10':require('../assets/menuItems/seeds.jpg'),
        '11':require('../assets/menuItems/spices.jpg'),
        '12':require('../assets/menuItems/ginger.jpg'),
        '13':require('../assets/menuItems/oranges.jpg'),
        '14':require('../assets/menuItems/lemons.jpg'),
        '15':require('../assets/menuItems/almonds.jpg'),
        '16':require('../assets/menuItems/acidic.jpg'),
        '17':require('../assets/menuItems/bsd.jpg'),
        '18':require('../assets/menuItems/highfiber.jpg'),
        '19':require('../assets/menuItems/antiaging.jpg'),
        '20':require('../assets/menuItems/sukumawiki.jpg'),
        '21':require('../assets/menuItems/wildmeat.jpg'),
        '22':require('../assets/menuItems/apple.jpg'),
    },
    pageTitle:{
        '1':'Beef',
        '2':'Pork',
        '3':'Goat',
        '4':'Sheep',
        '5':'Chicken',
        '6':'Duck',
        '7':'Fish',
        '8':'Fruits',
        '9':'Vegetables',
        '10':'Seeds',
        '11':'Spices',
        '12':'Ginger',
        '13':'Oranges',
        '14':'Lemons',
        '15':'Almonds',
        '16':'Acidic foods',
        '17':'Better sex drive',
        '18':'High Fiber foods',
        '19':'Anti aging foods',
        '20':'Sukumawiki',
        '21':'Wild meat',
        '22':'Apple',
    }
}

export const footItemStats = {
    '1':{
        'gram':100,
        nutritionalInformation:[
          {name:'Energy',value:250,key:'1',unit:'kcal'},
          {name:'Fat',value:15,key:'2',unit:'g'},
          {name:'Colesterol',value:90,key:'3',unit:'mg'},
          {name:'Protein',value:26,key:'4',unit:'g'},
        ],
        vitamins:[
            {name:'Vitamin B6',value:0.4,key:'1'},
            {name:'Vitamin C',value:0,key:'2'},
        ],
        minerals:[
            {name:'Calcium',value:1,key:'1'},
            {name:'Iron',value:20,key:'2'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '2':{
        'gram':85,
        nutritionalInformation:[
            {name:'Energy',value:99,key:'1',unit:'kcal'},
            {name:'Carbs',value:0.3,key:'2',unit:'g'},
            {name:'Fat',value:2.7,key:'3',unit:'g'},
            {name:'Protein',value:18.4,key:'4',unit:'g'},
            {name:'Omega 3',value:10.2,key:'5',unit:'mg'},
            {name:'Omega 6',value:324,key:'6',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin E',value:1,key:'1'},
            {name:'Thiamin B1',value:58,key:'2'},
            {name:'Riboflavin B2',value:23,key:'3'},
            {name:'Niacin B3',value:39.4,key:'4'},
            {name:'Pathothenic acid',value:11.7,key:'5'},
            {name:'Vitamin B6',value:38,key:'6'},
            {name:'Vitamin B12',value:16.7,key:'7'},
            {name:'Choline',value:11.4,key:'8'},
        ],
        minerals:[
            {name:'Calcium',value:0.4,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:10,key:'3'},
            {name:'Magnesium',value:5,key:'4'},
            {name:'Phosphorus',value:27,key:'5'},
            {name:'Potassium',value:12.7,key:'6'},
            {name:'Selenium',value:55.4,key:'7'},
            {name:'Sodium',value:13,key:'8'},
            {name:'Zinc',value:15.5,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '3':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:200,key:'1',unit:'kcal'},
            {name:'Fat',value:418,key:'2',unit:'kj'},
            {name:'Protein',value:461,key:'3',unit:'kj'},
            {name:'Omega 3',value:140,key:'4',unit:'mg'},
            {name:'Omega 6',value:400,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin E',value:4,key:'1'},
            {name:'Thiamin B1',value:4,key:'2'},
            {name:'Riboflavin B2',value:18,key:'3'},
            {name:'Niacin B3',value:33,key:'4'},
            {name:'Pathothenic acid',value:9,key:'5'},
            {name:'Vitamin B6',value:19,key:'6'},
            {name:'Vitamin B12',value:74,key:'7'},
        ],
        minerals:[
            {name:'Calcium',value:1,key:'1'},
            {name:'Copper',value:3,key:'2'},
            {name:'Iron',value:26,key:'3'},
            {name:'Magnesium',value:8,key:'4'},
            {name:'Phosphorus',value:27,key:'5'},
            {name:'Potassium',value:12,key:'6'},
            {name:'Selenium',value:54,key:'7'},
            {name:'Sodium',value:6,key:'8'},
            {name:'Zinc',value:40,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '4':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:234,key:'1',unit:'kcal'},
            {name:'Fat',value:418,key:'2',unit:'kj'},
            {name:'Protein',value:561,key:'3',unit:'kj'},
            {name:'Omega 3',value:147,key:'4',unit:'mg'},
            {name:'Omega 6',value:421,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin E',value:4,key:'1'},
            {name:'Thiamin B1',value:4,key:'2'},
            {name:'Riboflavin B2',value:18,key:'3'},
            {name:'Niacin B3',value:33,key:'4'},
            {name:'Pathothenic acid',value:9,key:'5'},
            {name:'Vitamin B6',value:19,key:'6'},
            {name:'Vitamin B12',value:74,key:'7'},
        ],
        minerals:[
            {name:'Calcium',value:1,key:'1'},
            {name:'Copper',value:3,key:'2'},
            {name:'Iron',value:26,key:'3'},
            {name:'Magnesium',value:8,key:'4'},
            {name:'Phosphorus',value:27,key:'5'},
            {name:'Potassium',value:12,key:'6'},
            {name:'Selenium',value:54,key:'7'},
            {name:'Sodium',value:6,key:'8'},
            {name:'Zinc',value:40,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '5':{
        'gram':100,
        nutritionalInformation:[
          {name:'Energy',value:250,key:'1',unit:'kcal'},
          {name:'Fat',value:13,key:'2',unit:'g'},
          {name:'Protein',value:13,key:'3',unit:'g'},
        ],
        vitamins:[
            {name:'Vitamin A',value:6,key:'1'},
            {name:'Pathothenic acid',value:13,key:'5'},
        ],
        minerals:[
            {name:'Sodium',value:4,key:'1'},
            {name:'Iron',value:9,key:'2'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '6':{
        'gram':85,
        nutritionalInformation:[
            {name:'Energy',value:165,key:'1',unit:'kcal'},
            {name:'Fat',value:9.5,key:'2',unit:'g'},
            {name:'Protein',value:20,key:'3',unit:'g'},
            {name:'Omega 3',value:119,key:'4',unit:'mg'},
            {name:'Omega 6',value:1096,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:2.2,key:'1'},
            {name:'Vitamin E',value:6,key:'2'},
            {name:'Vitamin K',value:4.6,key:'3'},
            {name:'Thiamin B1',value:25,key:'4'},
            {name:'Riboflavin B2',value:30,key:'5'},
            {name:'Niacin B3',value:27,key:'6'},
            {name:'Pathothenic acid',value:22,key:'7'},
            {name:'Vitamin B6',value:23,key:'8'},
            {name:'Vitamin B12',value:12,key:'9'},
            {name:'Folate',value:2,key:'10'},
            {name:'Choline',value:10,key:'11'},
        ],
        minerals:[
            {name:'Calcium',value:1,key:'1'},
            {name:'Copper',value:22,key:'2'},
            {name:'Iron',value:28,key:'3'},
            {name:'Magnesium',value:4,key:'4'},
            {name:'Phosphorus',value:18,key:'5'},
            {name:'Potassium',value:5,key:'6'},
            {name:'Selenium',value:27,key:'7'},
            {name:'Sodium',value:4,key:'8'},
            {name:'Zinc',value:20,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '7':{
        'gram':85,
        nutritionalInformation:[
            {name:'Energy',value:149,key:'1',unit:'kcal'},
            {name:'Fat',value:5.4,key:'2',unit:'g'},
            {name:'Protein',value:25.4,key:'3',unit:'g'},
            {name:'Omega 3',value:141,key:'4',unit:'mg'},
            {name:'Omega 6',value:57,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:71,key:'1'},
            {name:'Thiamin B1',value:25,key:'2'},
            {name:'Riboflavin B2',value:33,key:'3'},
            {name:'Niacin B3',value:55,key:'4'},
            {name:'Pathothenic acid',value:20,key:'5'},
            {name:'Vitamin B6',value:30,key:'6'},
            {name:'Vitamin B12',value:38,key:'7'},
            {name:'Folate',value:0.4,key:'8'},
        ],
        minerals:[
            {name:'Calcium',value:0.9,key:'1'},
            {name:'Copper',value:21,key:'2'},
            {name:'Iron',value:13,key:'3'},
            {name:'Magnesium',value:13,key:'4'},
            {name:'Phosphorus',value:28,key:'5'},
            {name:'Potassium',value:7,key:'6'},
            {name:'Selenium',value:56,key:'7'},
            {name:'Sodium',value:2.8,key:'8'},
            {name:'Zinc',value:6.4,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '8':{
        'gram':120,
        nutritionalInformation:[
            {name:'Energy',value:60.1,key:'1',unit:'kcal'},
            {name:'Glycerin',value:38,key:'2',unit:'g'},
            {name:'Carbs',value:16.5,key:'3',unit:'g'},
            {name:'Omega 3',value:10,key:'4',unit:'mg'},
            {name:'Omega 6',value:51,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin C',value:12.2,key:'1'},
            {name:'Vitamin E',value:2,key:'2'},
            {name:'Vitamin K',value:3.7,key:'3'},
            {name:'Vitamin A',value:2.2,key:'4'},
            {name:'Niacin B3',value:0.6,key:'5'},
            {name:'Pathothenic acid',value:1.7,key:'6'},
            {name:'Vitamin B6',value:7.7,key:'7'},
            {name:'Choline',value:0.9,key:'8'},
            {name:'Folate',value:0.9,key:'9'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '9':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:62,key:'1',unit:'kcal'},
            {name:'Glycerin',value:32,key:'2',unit:'g'},
            {name:'Carbs',value:10,key:'3',unit:'g'},
            {name:'Omega 3',value:30,key:'4',unit:'mg'},
            {name:'Omega 6',value:42,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:11,key:'1'},
            {name:'Vitamin B',value:5,key:'2'},
            {name:'Vitamin K',value:3,key:'3'},
            {name:'Vitamin A',value:2,key:'4'},
            {name:'Niacin B3',value:1,key:'5'},
            {name:'Pathothenic acid',value:1.7,key:'6'},
            {name:'Vitamin B6',value:7,key:'7'},
            {name:'Choline',value:2,key:'8'},
            {name:'Folate',value:2,key:'9'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '10':{
        'gram':50,
        nutritionalInformation:[
            {name:'Energy',value:62,key:'1',unit:'kcal'},
            {name:'Glycerin',value:32,key:'2',unit:'g'},
            {name:'Carbs',value:10,key:'3',unit:'g'},
            {name:'Omega 3',value:30,key:'4',unit:'mg'},
            {name:'Omega 6',value:42,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:11,key:'1'},
            {name:'Vitamin B',value:5,key:'2'},
            {name:'Vitamin K',value:3,key:'3'},
            {name:'Vitamin A',value:2,key:'4'},
            {name:'Niacin B3',value:1,key:'5'},
            {name:'Pathothenic acid',value:1.7,key:'6'},
            {name:'Vitamin B6',value:7,key:'7'},
            {name:'Choline',value:2,key:'8'},
            {name:'Folate',value:2,key:'9'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '11':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:62,key:'1',unit:'kcal'},
            {name:'Glycerin',value:32,key:'2',unit:'g'},
            {name:'Carbs',value:10,key:'3',unit:'g'},
            {name:'Omega 3',value:30,key:'4',unit:'mg'},
            {name:'Omega 6',value:42,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:11,key:'1'},
            {name:'Vitamin B',value:5,key:'2'},
            {name:'Vitamin K',value:3,key:'3'},
            {name:'Vitamin A',value:2,key:'4'},
            {name:'Niacin B3',value:1,key:'5'},
            {name:'Pathothenic acid',value:1.7,key:'6'},
            {name:'Vitamin B6',value:7,key:'7'},
            {name:'Choline',value:2,key:'8'},
            {name:'Folate',value:2,key:'9'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '12':{
        'gram':120,
        nutritionalInformation:[
            {name:'Energy',value:57,key:'1',unit:'kcal'},
            {name:'Glycerin',value:42,key:'2',unit:'g'},
            {name:'Carbs',value:14,key:'3',unit:'g'},
            {name:'Fiber',value:2.6,key:'4',unit:'g'},
            {name:'Protein',value:1.3,key:'5',unit:'g'},
            {name:'Omega 3',value:8.5,key:'6',unit:'mg'},
            {name:'Omega 6',value:21,key:'7',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:4.8,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:2.9,key:'4'},
            {name:'Phosphorus',value:1.7,key:'5'},
            {name:'Potassium',value:5.8,key:'6'},
            {name:'Selenium',value:0.9,key:'7'},
            {name:'Zinc',value:1,key:'8'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '13':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:57,key:'1',unit:'kcal'},
            {name:'Glycerin',value:42,key:'2',unit:'g'},
            {name:'Carbs',value:14,key:'3',unit:'g'},
            {name:'Fiber',value:2.6,key:'4',unit:'g'},
            {name:'Protein',value:1.3,key:'5',unit:'g'},
            {name:'Omega 3',value:8.5,key:'6',unit:'mg'},
            {name:'Omega 6',value:21,key:'7',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:4.8,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:2.9,key:'4'},
            {name:'Phosphorus',value:1.7,key:'5'},
            {name:'Potassium',value:5.8,key:'6'},
            {name:'Selenium',value:0.9,key:'7'},
            {name:'Zinc',value:1,key:'8'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '14':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:57,key:'1',unit:'kcal'},
            {name:'Glycerin',value:42,key:'2',unit:'g'},
            {name:'Carbs',value:14,key:'3',unit:'g'},
            {name:'Fiber',value:2.6,key:'4',unit:'g'},
            {name:'Protein',value:1.3,key:'5',unit:'g'},
            {name:'Omega 3',value:8.5,key:'6',unit:'mg'},
            {name:'Omega 6',value:21,key:'7',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:4.8,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:2.9,key:'4'},
            {name:'Phosphorus',value:1.7,key:'5'},
            {name:'Potassium',value:5.8,key:'6'},
            {name:'Selenium',value:0.9,key:'7'},
            {name:'Zinc',value:1,key:'8'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '15':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:57,key:'1',unit:'kcal'},
            {name:'Glycerin',value:42,key:'2',unit:'g'},
            {name:'Carbs',value:14,key:'3',unit:'g'},
            {name:'Fiber',value:2.6,key:'4',unit:'g'},
            {name:'Protein',value:1.3,key:'5',unit:'g'},
            {name:'Omega 3',value:8.5,key:'6',unit:'mg'},
            {name:'Omega 6',value:21,key:'7',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:4.8,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:2.9,key:'4'},
            {name:'Phosphorus',value:1.7,key:'5'},
            {name:'Potassium',value:5.8,key:'6'},
            {name:'Selenium',value:0.9,key:'7'},
            {name:'Zinc',value:1,key:'8'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '16':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:62,key:'1',unit:'kcal'},
            {name:'Glycerin',value:32,key:'2',unit:'g'},
            {name:'Carbs',value:10,key:'3',unit:'g'},
            {name:'Omega 3',value:30,key:'4',unit:'mg'},
            {name:'Omega 6',value:42,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '17':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:62,key:'1',unit:'kcal'},
            {name:'Glycerin',value:32,key:'2',unit:'g'},
            {name:'Carbs',value:10,key:'3',unit:'g'},
            {name:'Omega 3',value:30,key:'4',unit:'mg'},
            {name:'Omega 6',value:42,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '18':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:62,key:'1',unit:'kcal'},
            {name:'Glycerin',value:32,key:'2',unit:'g'},
            {name:'Carbs',value:10,key:'3',unit:'g'},
            {name:'Omega 3',value:30,key:'4',unit:'mg'},
            {name:'Omega 6',value:42,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '19':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:62,key:'1',unit:'kcal'},
            {name:'Glycerin',value:32,key:'2',unit:'g'},
            {name:'Carbs',value:10,key:'3',unit:'g'},
            {name:'Omega 3',value:30,key:'4',unit:'mg'},
            {name:'Omega 6',value:42,key:'5',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin A',value:9,key:'1'},
            {name:'Vitamin C',value:140,key:'2'},
            {name:'Vitamin E',value:2,key:'3'},
            {name:'Thiamin B1',value:8.3,key:'4'},
            {name:'Riboflavin B2',value:7.7,key:'5'},
            {name:'Niacin B3',value:1.9,key:'6'},
            {name:'Pathothenic acid',value:5,key:'7'},
            {name:'Vitamin B6',value:7.7,key:'8'},
            {name:'Choline',value:2,key:'9'},
            {name:'Folate',value:9,key:'10'},
        ],
        minerals:[
            {name:'Calcium',value:0.7,key:'1'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:1.4,key:'4'},
            {name:'Phosphorus',value:4.3,key:'5'},
            {name:'Potassium',value:3.4,key:'6'},
            {name:'Sodium',value:0.1,key:'8'},
            {name:'Zinc',value:0.9,key:'9'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '20':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:57,key:'1',unit:'kcal'},
            {name:'Glycerin',value:42,key:'2',unit:'g'},
            {name:'Carbs',value:14,key:'3',unit:'g'},
            {name:'Fiber',value:2.6,key:'4',unit:'g'},
            {name:'Protein',value:1.3,key:'5',unit:'g'},
            {name:'Omega 3',value:8.5,key:'6',unit:'mg'},
            {name:'Omega 6',value:21,key:'7',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin C',value:12.2,key:'1'},
            {name:'Vitamin E',value:2,key:'2'},
            {name:'Vitamin K',value:3.7,key:'3'},
            {name:'Vitamin A',value:2.2,key:'4'},
            {name:'Niacin B3',value:0.6,key:'5'},
            {name:'Pathothenic acid',value:1.7,key:'6'},
            {name:'Vitamin B6',value:7.7,key:'7'},
            {name:'Choline',value:0.9,key:'8'},
            {name:'Folate',value:0.9,key:'9'},
        ],
        minerals:[
            {name:'Calcium',value:4.8,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:2.9,key:'4'},
            {name:'Phosphorus',value:1.7,key:'5'},
            {name:'Potassium',value:5.8,key:'6'},
            {name:'Selenium',value:0.9,key:'7'},
            {name:'Zinc',value:1,key:'8'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '21':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:57,key:'1',unit:'kcal'},
            {name:'Glycerin',value:42,key:'2',unit:'g'},
            {name:'Carbs',value:14,key:'3',unit:'g'},
            {name:'Fiber',value:2.6,key:'4',unit:'g'},
            {name:'Protein',value:1.3,key:'5',unit:'g'},
            {name:'Omega 3',value:8.5,key:'6',unit:'mg'},
            {name:'Omega 6',value:21,key:'7',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin C',value:12.2,key:'1'},
            {name:'Vitamin E',value:2,key:'2'},
            {name:'Vitamin K',value:3.7,key:'3'},
            {name:'Vitamin A',value:2.2,key:'4'},
            {name:'Niacin B3',value:0.6,key:'5'},
            {name:'Pathothenic acid',value:1.7,key:'6'},
            {name:'Vitamin B6',value:7.7,key:'7'},
            {name:'Choline',value:0.9,key:'8'},
            {name:'Folate',value:0.9,key:'9'},
        ],
        minerals:[
            {name:'Calcium',value:4.8,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:2.9,key:'4'},
            {name:'Phosphorus',value:1.7,key:'5'},
            {name:'Potassium',value:5.8,key:'6'},
            {name:'Selenium',value:0.9,key:'7'},
            {name:'Zinc',value:1,key:'8'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
    '22':{
        'gram':100,
        nutritionalInformation:[
            {name:'Energy',value:57,key:'1',unit:'kcal'},
            {name:'Glycerin',value:42,key:'2',unit:'g'},
            {name:'Carbs',value:14,key:'3',unit:'g'},
            {name:'Fiber',value:2.6,key:'4',unit:'g'},
            {name:'Protein',value:1.3,key:'5',unit:'g'},
            {name:'Omega 3',value:8.5,key:'6',unit:'mg'},
            {name:'Omega 6',value:21,key:'7',unit:'mg'},
        ],
        vitamins:[
            {name:'Vitamin C',value:12.2,key:'1'},
            {name:'Vitamin E',value:2,key:'2'},
            {name:'Vitamin K',value:3.7,key:'3'},
            {name:'Vitamin A',value:2.2,key:'4'},
            {name:'Niacin B3',value:0.6,key:'5'},
            {name:'Pathothenic acid',value:1.7,key:'6'},
            {name:'Vitamin B6',value:7.7,key:'7'},
            {name:'Choline',value:0.9,key:'8'},
            {name:'Folate',value:0.9,key:'9'},
        ],
        minerals:[
            {name:'Calcium',value:4.8,key:'1'},
            {name:'Copper',value:11,key:'2'},
            {name:'Iron',value:1.3,key:'3'},
            {name:'Magnesium',value:2.9,key:'4'},
            {name:'Phosphorus',value:1.7,key:'5'},
            {name:'Potassium',value:5.8,key:'6'},
            {name:'Selenium',value:0.9,key:'7'},
            {name:'Zinc',value:1,key:'8'},
        ],
        'pros':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        'cons':'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',

    },
}